"""Cat 021 Edition 2.7 UAP — Eurocontrol ADS-B Reports default profile."""

from app.asterix.uap import UapEntry

CAT021_UAP: tuple[UapEntry, ...] = (
    UapEntry(1, "010", "Data Source Identification", "2", "data_source", mandatory=True),
    UapEntry(2, "040", "Target Report Descriptor", "1+", "target_report_descriptor"),
    UapEntry(3, "161", "Track Number", "2", "track_number"),
    UapEntry(4, "015", "Service Identification", "1", "service_id"),
    UapEntry(5, "071", "Time of Applicability for Position", "3", "time_of_applicability_position"),
    UapEntry(6, "130", "Position in WGS-84 Co-ordinates", "6", "wgs84", related_field_ids=("position_resolution",)),
    UapEntry(7, "131", "High-Resolution Position in WGS-84", "8", "wgs84", related_field_ids=("position_resolution",)),
    UapEntry(8, "072", "Time of Applicability for Velocity", "3", "time_of_applicability_velocity"),
    UapEntry(9, "150", "Air Speed", "2", "air_speed"),
    UapEntry(10, "151", "True Air Speed", "2", "true_air_speed"),
    UapEntry(11, "080", "Target Address", "3", "target_address"),
    UapEntry(12, "073", "Time of Message Reception for Position", "3", "time_of_reception_position"),
    UapEntry(13, "074", "Time of Message Reception for Position (High Precision)", "4", "time_of_reception_position_hp"),
    UapEntry(14, "075", "Time of Message Reception for Velocity", "3", "time_of_reception_velocity"),
    UapEntry(15, "076", "Time of Message Reception for Velocity (High Precision)", "4", "time_of_reception_velocity_hp"),
    UapEntry(16, "140", "Geometric Height", "2", "geometric_height"),
    UapEntry(17, "090", "Quality Indicators", "1+", "quality_indicators"),
    UapEntry(18, "210", "MOPS Version", "1", "mops_version"),
    UapEntry(19, "070", "Mode 3/A Code in Octal Representation", "2", "mode3a", related_field_ids=("include_mode3a",)),
    UapEntry(20, "230", "Roll Angle", "2", "roll_angle"),
    UapEntry(21, "145", "Flight Level", "2", "flight_level", related_field_ids=("include_flight_level",)),
    UapEntry(22, "152", "Magnetic Heading", "2", "magnetic_heading"),
    UapEntry(23, "200", "Target Status", "1", "target_status"),
    UapEntry(24, "155", "Barometric Vertical Rate", "2", "barometric_vertical_rate"),
    UapEntry(25, "157", "Geometric Vertical Rate", "2", "geometric_vertical_rate"),
    UapEntry(26, "160", "Airborne Ground Vector", "4", "ground_vector"),
    UapEntry(27, "165", "Track Angle Rate", "2", "track_angle_rate"),
    UapEntry(28, "077", "Time of ASTERIX Report Transmission", "3", "time_of_report_transmission"),
    UapEntry(29, "170", "Target Identification", "6", "target_identification", related_field_ids=("include_target_identification",)),
    UapEntry(30, "020", "Emitter Category", "1", "emitter_category"),
    UapEntry(31, "220", "Met Information", "1+", "met_information"),
    UapEntry(32, "146", "Selected Altitude", "2", "selected_altitude"),
    UapEntry(33, "148", "Final State Selected Altitude", "2", "final_state_selected_altitude"),
    UapEntry(34, "110", "Trajectory Intent", "1+", "trajectory_intent"),
    UapEntry(35, "016", "Service Management", "1", "service_management"),
    UapEntry(36, "008", "Aircraft Operational Status", "1", "aircraft_operational_status"),
    UapEntry(37, "271", "Surface Capabilities and Characteristics", "1+", "surface_capabilities"),
    UapEntry(38, "132", "Message Amplitude", "1", "message_amplitude"),
    UapEntry(39, "250", "Mode S MB Data", "1+N×8", "mode_s_mb_data"),
    UapEntry(40, "260", "ACAS Resolution Advisory Report", "7", "acas_resolution_advisory"),
    UapEntry(41, "400", "Receiver ID", "1", "receiver_id"),
    UapEntry(42, "295", "Data Ages", "1+", "data_ages"),
    UapEntry(43, None, "Spare", "-", spare=True),
    UapEntry(44, None, "Spare", "-", spare=True),
    UapEntry(45, None, "Spare", "-", spare=True),
    UapEntry(46, None, "Spare", "-", spare=True),
    UapEntry(47, None, "Spare", "-", spare=True),
    UapEntry(48, "RE", "Reserved Expansion Field", "1+", "reserved_expansion"),
    UapEntry(49, "SP", "Special Purpose Field", "1+", "special_purpose"),
)
